-- Enable pgvector extension for embedding searches (future proofing)
create extension if not exists vector;

-- Create the Video Vault table
create table public.video_vault (
  id bigint generated by default as identity primary key,
  video_id text not null,
  title text not null,
  description text,
  transcript_snippet text,
  density_score numeric default 0,
  density_flags text[], -- Stored as array of strings
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate entries for the same video
  constraint video_vault_video_id_key unique (video_id)
);

-- Turn on Row Level Security (RLS)
alter table public.video_vault enable row level security;

-- Create a policy that allows anyone to read (since this is a public learning app)
create policy "Enable read access for all users"
on public.video_vault for select
using (true);

-- Create a policy that allows the service role (your API) to insert
create policy "Enable insert for service role"
on public.video_vault for insert
with check (true);

-- Optional: Create an index on video_id for faster lookups
create index idx_video_vault_video_id on public.video_vault (video_id);
